In [1]:
# Enter your code here. Read input from STDIN. Print output to STDOUT
from sklearn import svm
#from sklearn import linear_model
from sklearn.linear_model import LinearRegression
import numpy as np

first_line = input()
F = int(first_line.split(' ')[0])
N = int(first_line.split(' ')[1])

2 7


In [30]:
import matplotlib.pyplot as plt
from scipy import stats


In [11]:
x = []
y = []
for i in range(0, N):
    line = input().split(' ')
    xi = [float(l) for l in line[0:2]]
    yi = float(line[F])
    x.append(xi)
    y.append(yi)


0.18 0.89 109.85
1.0 0.26 155.72
0.92 0.11 137.66
0.07 0.37 76.17
0.85 0.16 139.75
0.99 0.41 162.6
0.87 0.47 151.77


In [12]:
print(x)
print(y)

x = np.array(x)
y = np.array(y)

print(x)
print(y)

[[0.18, 0.89], [1.0, 0.26], [0.92, 0.11], [0.07, 0.37], [0.85, 0.16], [0.99, 0.41], [0.87, 0.47]]
[109.85, 155.72, 137.66, 76.17, 139.75, 162.6, 151.77]
[[0.18 0.89]
 [1.   0.26]
 [0.92 0.11]
 [0.07 0.37]
 [0.85 0.16]
 [0.99 0.41]
 [0.87 0.47]]
[109.85 155.72 137.66  76.17 139.75 162.6  151.77]


In [14]:
print(x[0])
print(y[0])

[0.18 0.89]
109.85


In [22]:
clf = linear_model.LinearRegression()
clf.fit(x, y)

T = int(input())
t = []

for i in range(0, T):
    line = input().split(' ')
    ti = [float(l) for l in line[0:F]]
    t.append(ti)
t = np.array(t)
    

4
0.49 0.18
0.57 0.83
0.56 0.64
0.76 0.18


In [29]:
print(clf.coef_)
print(clf.intercept_)

[90.69331739 46.46296549]
52.41149904506085


In [23]:
print(t)

[[0.49 0.18]
 [0.57 0.83]
 [0.56 0.64]
 [0.76 0.18]]


In [36]:
model = clf.predict(t)
for i in clf.predict(t):
    print(i)

105.21455835106944
142.67095130729922
132.93605469124694
129.70175404502453
